name: quiz_game
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  english_words: ^4.0.0
  provider: ^6.0.0
  http: 0.13.6
  confetti: ^0.8.0  # ceci PERMET D'UTILISER les effets de confettis
  audioplayers: ^6.1.0
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Cette section pour les assets
  assets:
    - assets/QUIZ.png   # Indique le chemin vers l'image
    - assets/pngegg.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pngegg.png"  # Remplace par le chemin de ton icône